import '../models/listing.dart';

// Demo listings data - make sure this is exported
final List<Listing> demoListings = [
  Listing(
    id: '1',
    title: 'Office Chair - Good Condition',
    imageUrl: 'https://images.pexels.com/photos/276534/pexels-photo-276534.jpeg',
    price: 1500,
    location: 'Head Office, Floor 3',
    date: 'Today',
    category: 'Furniture',
    description: 'Comfortable office chair in good condition. Adjustable height and armrests. Perfect for home office setup.',
  ),
  Listing(
    id: '2',
    title: 'Dell Monitor 24 inch',
    imageUrl: 'https://images.pexels.com/photos/777001/pexels-photo-777001.jpeg',
    price: 5000,
    location: 'IT Department, Floor 2',
    date: 'Yesterday',
    category: 'Electronics',
    description: 'Full HD Dell monitor, 24 inches. Excellent display quality. Used for 2 years, no scratches or dead pixels.',
  ),
  Listing(
    id: '3',
    title: 'Programming Books Set',
    imageUrl: 'https://images.pexels.com/photos/1370295/pexels-photo-1370295.jpeg',
    price: 800,
    location: 'Library, Floor 1',
    date: '2 days ago',
    category: 'Books',
    description: 'Collection of programming books including Python, JavaScript, and Data Structures. Great for beginners.',
  ),
  Listing(
    id: '4',
    title: 'Free Office Supplies',
    imageUrl: 'https://images.pexels.com/photos/265672/pexels-photo-265672.jpeg',
    price: 0,
    location: 'Storage Room',
    date: 'Today',
    category: 'Other',
    isDonation: true,
    description: 'Various office supplies including pens, notebooks, folders. Free to anyone who needs them.',
  ),
  Listing(
    id: '5',
    title: 'Laptop Stand',
    imageUrl: 'https://images.pexels.com/photos/7532098/pexels-photo-7532098.jpeg',
    price: 600,
    location: 'Marketing, Floor 4',
    date: '3 days ago',
    category: 'Electronics',
    description: 'Adjustable laptop stand made of aluminum. Great for improving posture while working.',
  ),
  Listing(
    id: '6',
    title: 'Wireless Keyboard',
    imageUrl: 'https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg',
    price: 1200,
    location: 'Development Team',
    date: '1 week ago',
    category: 'Electronics',
    description: 'Logitech wireless keyboard with long battery life. Barely used, like new condition.',
  ),
  Listing(
    id: '7',
    title: 'Desk Lamp',
    imageUrl: 'https://images.pexels.com/photos/1112598/pexels-photo-1112598.jpeg',
    price: 450,
    location: 'Workspace B',
    date: '4 days ago',
    category: 'Furniture',
    description: 'Modern LED desk lamp with adjustable brightness. Energy efficient and sleek design.',
  ),
  Listing(
    id: '8',
    title: 'Business Books Collection',
    imageUrl: 'https://images.pexels.com/photos/1288484/pexels-photo-1288484.jpeg',
    price: 1000,
    location: 'HR Department',
    date: '5 days ago',
    category: 'Books',
    description: 'Set of 5 business and management books. Great for professional development.',
  ),
  Listing(
    id: '9',
    title: 'Free Plant for Office',
    imageUrl: 'https://images.pexels.com/photos/1084199/pexels-photo-1084199.jpeg',
    price: 0,
    location: 'Reception',
    date: 'Today',
    category: 'Other',
    isDonation: true,
    description: 'Indoor plant perfect for office decoration. Comes with pot. Easy to maintain.',
  ),
  Listing(
    id: '10',
    title: 'Whiteboard',
    imageUrl: 'https://images.pexels.com/photos/3184317/pexels-photo-3184317.jpeg',
    price: 800,
    location: 'Conference Room 2',
    date: '1 week ago',
    category: 'Other',
    description: 'Large whiteboard 4x3 feet. Perfect for meetings and brainstorming sessions. Includes markers.',
  ),
];